name: Emscripten version
on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
  build:
    emsdk-ver: 3.1.19
    name: Emscripten version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache emsdk
        id: cache-emsdk
        uses: actions/cache@v3
        with:
          path: emsdk
          key: ${{ runner.os }}-${{ emsdk-ver }}

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential git

      - if: ${{ steps.cache-emsdk.outputs.cache-hit != 'true' }}
        name: Prep
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${{ emsdk-ver }}
          ./emsdk activate ${{ emsdk-ver }}
          mkdir env

      - name: Build
        run: |
          cd emsdk
          export WORKSPACE="${{github.workspace}}/emsdk/env"
          ../contrib/instead-em-build.sh
          mkdir -p ../release/instead-em
          cp env/instead-em-js/instead-em.* ../release/instead-em
          cp env/instead-em-js/load* ../release/instead-em
          cp env/instead-em-js/*.svg ../release/instead-em

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: instead-em
          path: release
          retention-days: 1
