name: Emscripten version
on:
  schedule:
    - cron:  '30 21 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Emscripten version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential git

      - name: Prep
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install 3.1.19
          ./emsdk activate 3.1.19
          mkdir env

      - name: Build
        run: |
          cd emsdk
          export WORKSPACE="${{github.workspace}}/emsdk/env"
          ../contrib/instead-em-build.sh
          mkdir -p ../release/instead-em
          cp env/instead-em-js/instead-em.* ../release/instead-em
          cp env/instead-em-js/load* ../release/instead-em
          cp env/instead-em-js/*.svg ../release/instead-em

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: instead-em
          path: release
          retention-days: 1
