name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Standalone
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y liblua5.1-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
          sudo apt-get install -y build-essential debhelper

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DSTANDALONE=1 -DWITH_LUAJIT=0

      - name: Build
        run: cmake --build ./build --config Release

      - name: Create Artifact
        run: |
          cmake --install ./build

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: standalone
          path: build/standalone
